//! Agent configuration.
//!
//! [`AgentConfig`] is a serializable struct holding all agent parameters.
//! Used by [`super::AgentBuilder`] to construct an [`super::Agent`].

use crate::{AgentId, config::hooks::HooksConfig};
use crabllm_core::ToolChoice;
use crabllm_core::anthropic;
use proto::AgentInfo;
use serde::{Deserialize, Serialize};

/// Name of the built-in agent seeded on first run.
pub const DEFAULT_AGENT: &str = "crab";

/// Default maximum iterations for agent execution.
const DEFAULT_MAX_ITERATIONS: usize = 16;

/// Default max byte length for tool results during compaction.
const DEFAULT_COMPACT_TOOL_MAX_LEN: usize = 1024;

/// Default reasoning allowance when thinking is on.
const DEFAULT_THINKING_BUDGET: u32 = 4096;

/// Serializable agent configuration.
///
/// Contains all parameters for an agent: identity, model, iteration limits,
/// and delegation scope. Used both as the TOML deserialization target and
/// the runtime agent definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    /// Stable ULID identity. A fresh ULID is generated by
    /// [`AgentConfig::new`] / the protocol create handler when missing.
    #[serde(default)]
    pub id: AgentId,
    /// The label a person types. Stored with the record: the name index
    /// resolves it to an id, and every cleanup path needs the record to
    /// know which index key was its own.
    #[serde(default)]
    pub name: String,
    /// Who the agent is.
    #[serde(default)]
    pub description: String,
    /// Model to use from the registry. Required — every agent runs against
    /// a specific model. Empty string is rejected by the provider registry.
    #[serde(default)]
    pub model: String,
    /// Maximum iterations before stopping.
    #[serde(default = "default_max_iterations")]
    pub max_iterations: usize,
    /// Controls which tool the model calls. Defaults to `Auto`.
    #[serde(default)]
    pub tool_choice: ToolChoice,
    /// Whether to enable thinking/reasoning mode.
    #[serde(default)]
    pub thinking: bool,
    /// Output allowance for one response, before any reasoning budget. A whole
    /// HTML document written as a tool argument does not fit the default.
    #[serde(default = "default_max_tokens")]
    pub max_tokens: u32,
    /// Reasoning allowance when `thinking` is on — see
    /// [`AgentConfig::token_budget`].
    #[serde(default = "default_thinking_budget")]
    pub thinking_budget: u32,
    /// Skill names this agent can access. Empty = all skills (crabtalk default).
    #[serde(default)]
    pub skills: Vec<String>,
    /// MCP servers this agent uses. Each entry is a self-contained config the
    /// daemon spawns or connects to on the agent's behalf. Empty = none.
    #[serde(default)]
    pub mcps: Vec<crate::config::McpServerConfig>,
    /// Harnesses this agent uses, and what bounds each. Their tools join
    /// this agent's tool list under their own names. Empty = none.
    #[serde(default)]
    pub harnesses: Vec<crate::config::HarnessConfig>,
    /// Computed tool whitelist. Empty = all tools. Not serialized.
    #[serde(skip)]
    pub tools: Vec<String>,
    /// Max byte length to keep from tool-role messages when compacting.
    /// Longer results are truncated before sending to the compaction LLM.
    #[serde(default = "default_compact_tool_max_len")]
    pub compact_tool_max_len: usize,
    /// Harness configuration for this agent (memory recall limit, etc.).
    /// Each agent owns its own hook state — there is no global override.
    #[serde(default)]
    pub hooks: HooksConfig,
}

impl AgentConfig {
    /// Construct the default `crab` agent with the given model. Its id is
    /// the zero ULID — the one agent whose identity is a constant.
    pub fn crab(model: impl Into<String>) -> Self {
        let mut cfg = AgentConfig::new(DEFAULT_AGENT);
        cfg.id = AgentId::default();
        cfg.model = model.into();
        cfg.harnesses = vec![
            crate::HarnessConfig {
                name: "os".to_owned(),
                root: Some(crate::Root::Home),
                hosts: Vec::new(),
            },
            crate::HarnessConfig {
                name: "sessions".to_owned(),
                root: None,
                hosts: Vec::new(),
            },
        ];
        cfg
    }

    /// Create a new config with the given name, a fresh ULID, and
    /// defaults for everything else.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: AgentId::new(),
            name: name.into(),
            ..Default::default()
        }
    }

    /// Set the description, which is also the system message.
    pub fn description(mut self, desc: impl Into<String>) -> Self {
        self.description = desc.into();
        self
    }

    /// Set the model to use from the registry.
    pub fn model(mut self, name: impl Into<String>) -> Self {
        self.model = name.into();
        self
    }

    /// Enable or disable thinking/reasoning mode.
    pub fn thinking(mut self, enabled: bool) -> Self {
        self.thinking = enabled;
        self
    }

    /// For extended thinking `max_tokens` is the TOTAL budget, so the reasoning
    /// allowance is added to the output allowance rather than carved out of it.
    pub fn token_budget(&self) -> (u32, Option<anthropic::ThinkingConfig>) {
        let thinking = self.thinking.then(|| anthropic::ThinkingConfig {
            kind: "enabled".to_string(),
            budget_tokens: Some(self.thinking_budget),
        });
        let max_tokens = self.max_tokens + thinking.as_ref().map_or(0, |_| self.thinking_budget);
        (max_tokens, thinking)
    }
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            id: AgentId::default(),
            name: String::new(),
            description: String::new(),
            model: String::new(),
            max_iterations: DEFAULT_MAX_ITERATIONS,
            tool_choice: ToolChoice::Auto,
            thinking: false,
            max_tokens: crabllm_core::anthropic::DEFAULT_MAX_TOKENS,
            thinking_budget: DEFAULT_THINKING_BUDGET,
            skills: Vec::new(),
            harnesses: Vec::new(),
            mcps: Vec::new(),
            tools: Vec::new(),
            compact_tool_max_len: DEFAULT_COMPACT_TOOL_MAX_LEN,
            hooks: HooksConfig::default(),
        }
    }
}

impl From<AgentConfig> for AgentInfo {
    fn from(config: AgentConfig) -> Self {
        let conf = serde_json::to_string(&config).unwrap_or_default();
        Self {
            id: config.id.to_string(),
            name: config.name,
            description: config.description,
            config: conf,
            model: config.model,
            max_iterations: config.max_iterations as u32,
            thinking: config.thinking,
            skills: config.skills,
            mcps: config.mcps.iter().map(|m| m.name.clone()).collect(),
            compact_tool_max_len: config.compact_tool_max_len as u32,
        }
    }
}

fn default_max_iterations() -> usize {
    DEFAULT_MAX_ITERATIONS
}

fn default_max_tokens() -> u32 {
    crabllm_core::anthropic::DEFAULT_MAX_TOKENS
}

fn default_thinking_budget() -> u32 {
    DEFAULT_THINKING_BUDGET
}

fn default_compact_tool_max_len() -> usize {
    DEFAULT_COMPACT_TOOL_MAX_LEN
}
