[package]
name = "crabtalk-transport"
description = "UDS and TCP transport for Crabtalk daemon communication"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/crabtalk-transport"
keywords.workspace = true

[dependencies]
proto = { workspace = true, features = ["client", "server"] }
prost = { workspace = true, features = ["std"] }

# crates.io
anyhow.workspace = true
async-stream.workspace = true
futures-core.workspace = true
futures-util.workspace = true
tokio.workspace = true
tracing.workspace = true
