[package]
name = "crabtalk-store"
description = "Persistence for Crabtalk"
documentation = "https://docs.rs/crabtalk-store"
readme = "README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
crabllm-core.workspace = true
proto = { workspace = true, features = ["llm", "std"] }
skill.workspace = true

anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
ulid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
