//! Provider configuration.
//!
//! `ProviderConfig` and `ApiStandard` are defined in wcore and re-exported here.
//! `Loader` selects which mistralrs builder to use for local models.

use compact_str::CompactString;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

pub use wcore::config::provider::{ApiStandard, ProviderConfig};

/// Selects which mistralrs model builder to use for local inference.
///
/// Defaults to `Text` when omitted in config.
#[derive(Debug, Serialize, Deserialize, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum Loader {
    /// `TextModelBuilder` — standard text models.
    #[default]
    Text,
    /// `GgufModelBuilder` — GGUF quantized models.
    Gguf,
    /// `VisionModelBuilder` — vision-language models.
    Vision,
}

/// Custom HuggingFace model configuration for local inference.
///
/// Allows users to run any HuggingFace model not in the built-in registry.
/// Memory and quantization are auto-selected at runtime based on system RAM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HfModelConfig {
    /// HuggingFace repository ID (e.g. `"myorg/MyModel-7B-GGUF"`).
    pub model_id: String,
    /// Which mistralrs builder to use.
    #[serde(default)]
    pub loader: Loader,
    /// Explicit GGUF filename (required for GGUF models without a standard
    /// naming convention).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gguf_file: Option<String>,
    /// Custom chat template override.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chat_template: Option<String>,
}

/// Model provider configuration for the daemon.
///
/// Remote providers are configured in `providers`. Local models come from the
/// built-in registry or from user-defined `models`. The active model name
/// lives in `[walrus].model`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ModelConfig {
    /// Optional embedding model
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub embedding: Option<CompactString>,
    /// Remote providers (local models come from the built-in registry)
    #[serde(default)]
    pub providers: BTreeMap<CompactString, ProviderConfig>,
    /// Custom HuggingFace models for local inference
    #[serde(default)]
    pub models: BTreeMap<CompactString, HfModelConfig>,
}

// MemoryThreshold is generated by build.rs from registry TOML files.
include!(concat!(env!("OUT_DIR"), "/quantization.rs"));
